on: [push]
name: Commit preview

jobs:
  build-and-publish:
    name: Build and publish to Cloudflare
    uses: quiltmc/quiltmc.org/.github/workflows/commit-preview.yaml@actions-upgrade
    secrets: inherit
    permissions:
      contents: write
      actions: read
      deployments: write